export default {
  login: "vatsalp21",
  id: 76724709,
  node_id: "MDQ6VXNlcjc2NzI0NzA5",
  avatar_url: "https://avatars.githubusercontent.com/u/76724709?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/vatsalp21",
  html_url: "https://github.com/vatsalp21",
  followers_url: "https://api.github.com/users/vatsalp21/followers",
  following_url:
    "https://api.github.com/users/vatsalp21/following{/other_user}",
  gists_url: "https://api.github.com/users/vatsalp21/gists{/gist_id}",
  starred_url: "https://api.github.com/users/vatsalp21/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/vatsalp21/subscriptions",
  organizations_url: "https://api.github.com/users/vatsalp21/orgs",
  repos_url: "https://api.github.com/users/vatsalp21/repos",
  events_url: "https://api.github.com/users/vatsalp21/events{/privacy}",
  received_events_url: "https://api.github.com/users/vatsalp21/received_events",
  type: "User",
  site_admin: false,
  name: "Vatsal Pandey",
  company: "THWS",
  blog: "cutt.ly/vatsalpandey",
  location: "Bangalore",
  email: null,
  hireable: null,
  bio: "async existence",
  twitter_username: "_vatsalpandey",
  public_repos: 15,
  public_gists: 0,
  followers: 4,
  following: 1,
  created_at: "2020-12-29T07:04:04Z",
  updated_at: "2024-06-23T10:55:16Z",
};
